# Generated by Django 4.1.7 on 2023-06-25 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=225)),
                ('item_desc', models.CharField(max_length=225)),
                ('item_price', models.IntegerField()),
            ],
        ),
    ]
