# Generated by Django 4.1.7 on 2023-06-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_YHjt58oZTWcHtJNFP6tAUKTAOdZE7rAHpD4N7KOs&s', max_length=500),
        ),
    ]
